fix: add check before reading a link
beaker-project/beaker-system-scan pull request #3
Opened 2020-10-26 16:07 UTC by mdujava

this should eliminate Stacktrace when interface under /sys/class/net is not a
symlink, as now we check before dereferencing to make sure file is a symlink.

Signed-off-by: Matej Dujava <mdujava@redhat.com>

2020-10-26 18:39 UTC, danrodrig requested changes
For context, would be good to have reference to the bugzilla in the message.

2020-10-26 18:39 UTC, danrodrig commented on systemscan/main.py
> +        if (iface.is_symlink() and 'virtual' in os.readlink(iface_path))
Same as before, `iface` is a string and only the entry name, not the full path,
```suggestion
        if (os.path.islink(iface_path) and 'virtual' in os.readlink(iface_path))
```

2020-10-27 13:50 UTC, StykMartin requested changes
@danrodrig is correct.
https://docs.python.org/3/library/os.html#os.listdir
It does accept Path-like object, where you can use `is_dir()` for example, however, the return value is `string`

2020-11-06 16:59 UTC, mdujava commented
I just updated the code per your suggestions, and tested it on the x86 system.

2020-11-06 18:25 UTC, cbouchar commented on systemscan/main.py
> +        # skip if path is not a dir as later we relay on files inside it
Minor comment:    s/relay/rely/

2020-11-06 22:30 UTC, danrodrig commented
https://bugzilla.redhat.com/show_bug.cgi?id=1824201

Enterprise testing:
```
$ python -m pytest -v
================================= test session starts =================================
platform linux2 -- Python 2.7.18, pytest-4.6.11, py-1.9.0, pluggy-0.13.1 -- beaker-system-scan/venv/bin/python
cachedir: .pytest_cache
rootdir: beaker-system-scan
collected 9 items                                                                  

tests/test_systemscan.py::test_sample[hp-z420] PASSED                           [ 11%]
tests/test_systemscan.py::test_sample[hp-rx1620] PASSED                         [ 22%]
tests/test_systemscan.py::test_sample[dell-pe2550] PASSED                       [ 33%]
tests/test_systemscan.py::test_sample[s390-guest] PASSED                        [ 44%]
tests/test_systemscan.py::test_sample[apm-mustang] PASSED                       [ 55%]
tests/test_systemscan.py::test_sample[x86-kvm-guest] PASSED                     [ 66%]
tests/test_systemscan.py::test_zero_values_are_excluded_from_USBID_key PASSED   [ 77%]
tests/test_systemscan.py::test_diskspace_key_value PASSED                       [ 88%]
tests/test_systemscan.py::test_map_32bit_archs PASSED                           [100%]

============================== 9 passed in 0.18 seconds ===============================
```

2020-11-06 22:38 UTC, StykMartin commented
> https://bugzilla.redhat.com/show_bug.cgi?id=1824201
> 
> Enterprise testing:
> ```
> $ python -m pytest -v
> ================================= test session starts =================================
> platform linux2 -- Python 2.7.18, pytest-4.6.11, py-1.9.0, pluggy-0.13.1 -- beaker-system-scan/venv/bin/python
> cachedir: .pytest_cache
> rootdir: beaker-system-scan
> collected 9 items                                                                  
> 
> tests/test_systemscan.py::test_sample[hp-z420] PASSED                           [ 11%]
> tests/test_systemscan.py::test_sample[hp-rx1620] PASSED                         [ 22%]
> tests/test_systemscan.py::test_sample[dell-pe2550] PASSED                       [ 33%]
> tests/test_systemscan.py::test_sample[s390-guest] PASSED                        [ 44%]
> tests/test_systemscan.py::test_sample[apm-mustang] PASSED                       [ 55%]
> tests/test_systemscan.py::test_sample[x86-kvm-guest] PASSED                     [ 66%]
> tests/test_systemscan.py::test_zero_values_are_excluded_from_USBID_key PASSED   [ 77%]
> tests/test_systemscan.py::test_diskspace_key_value PASSED                       [ 88%]
> tests/test_systemscan.py::test_map_32bit_archs PASSED                           [100%]
> 
> ============================== 9 passed in 0.18 seconds ===============================
> ```

Looks very enterprise to me

2020-11-06 23:49 UTC, danrodrig commented
> Looks very enterprise to me

I help :dolphin: with :dolphin: affairs.

2020-11-11 09:26 UTC, mdujava commented
Hi, It should be fixed now.

2020-11-11 09:29 UTC, StykMartin approved these changes
🐬 👍🏻

2020-11-11 11:35 UTC, cbouchar approved these changes

2020-11-11 15:55 UTC, renanrodrigo approved these changes

2020-11-11 15:55 UTC, merged